dist: trusty
language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - composer install

script:
   - composer run check
